services:
  # Python Service
  python:
    build:
      context: ../../
      dockerfile: backend/Docker/customPython.dockerfile
    container_name: python-container
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: VAT_database
    restart: unless-stopped
    networks:
      - backend

  # PHP myadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

    restart: unless-stopped

  # MariaDB Service
  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: VAT_database
    volumes:
      - VAT_database:/var/lib/mysql
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  VAT_database:
    driver: local

networks:
  backend:
    driver: bridge
